### ISSUE TITLE
arm64设备运行报错

### ISSUE THREAD

**Issue by smilexxfire** [bigbugcc/SrunLogin#2]
设备是树莓派4B，系统及报错信息如下图
![image](https://user-images.githubusercontent.com/50986622/193433557-e62b7976-16c8-45ad-abc5-78b4f1488d0a.png)
在个人电脑（amd64）的设备上运行正常
![image](https://user-images.githubusercontent.com/50986622/193433566-e8c18df8-8aab-493c-8daa-c55b5de14c21.png)

**Comment by bigbugcc** [comment]
认证的这个IP还未释放，如果是之前用的先登录上去手动下线，十分钟后在试；或者扫一下换个静态IP。一般如果IP正常没被占用，用拨号的设备ping认证服务器有回应那么说明ip没问题，ping不通说明被占用了。

**Comment by smilexxfire** [comment]
是这样的，我重启wan口拿到个新ip后认证成功了，感谢！

**Comment by bigbugcc** [comment]
> 认证的这个IP还未释放，如果是之前用的先登录上去手动下线，十分钟后在试；或者扫一下换个静态IP。一般如果IP正常没被占用，用拨号的设备ping认证服务器有回应那么说明ip没问题，ping不通说明被占用了。

老哥 帮我个忙，给我一张Linux下运行成功的截图，amd64和arm64的，感谢

**Comment by smilexxfire** [comment]
![TN{S@S34 38)L8A$2A7)H 0](https://user-images.githubusercontent.com/50986622/193606523-df290b4f-8afa-4ff2-9512-6f93493cd9d9.png)
![7}4%}`8KY91I$VR0DT)HDSV](https://user-images.githubusercontent.com/50986622/193607291-bd446096-0ba3-4191-a6cd-175a369e8519.png)

**Comment by bigbugcc** [comment]
十分感谢
